# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev
  - stable

stages:
  - analyzer_and_format:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test: -j 1

travis:
  before_install:
    - export CHROMEDRIVER_BINARY=/usr/bin/google-chrome
    - export CHROMEDRIVER_ARGS=--no-sandbox
    - /usr/bin/google-chrome --version
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - export PATH=$PATH:$PWD
    - chromedriver --port=4444 --url-base=wd/hub &
