name: webdev
description: A CLI for Dart web development.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/webdev
version: 0.1.0-dev

environment:
  sdk: ">=2.0.0-dev.32.0 <2.0.0"

dependencies:
  args: ^1.2.0
  io: ^0.3.2+1
  pub_semver: ^1.3.2
  stack_trace: ^1.9.2
  yaml: ^2.1.13

dev_dependencies:
  path: ^1.5.1
  test: ^0.12.0
  test_descriptor: ^1.0.3
  test_process: ^1.0.1

executables:
  webdev:
